default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: TestEngine_development

test:
  <<: *default
  database: TestEngine_test

production:
  <<: *default
  database: TestEngine_production
  username: TestEngine
  password: <%= ENV['TESTENGINE_DATABASE_PASSWORD'] %>
